config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
<<<<<<< HEAD

=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
  devise_for :users

  resources :park_equipments, :only => :index do
    collection do
      get 'office'
      post 'office'
      post 'search_dep'
<<<<<<< HEAD
<<<<<<< HEAD
      get 'official'
      post 'official'
=======
=======
>>>>>>> origin/Klavakurochkina
      post 'create_branch'
      get 'create_branch'
      post 'create_department'
      get 'search_office'
      post 'search_office'
      get 'add_office'
      get 'delete_office'
<<<<<<< HEAD
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
<<<<<<< HEAD

>>>>>>> origin/Klavakurochkina
=======
>>>>>>> origin/Klavakurochkina
=======
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
>>>>>>> origin/Klavakurochkina
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
    end
  end

end

app/views/shared/_all_icons_user.haml
%li.visible-phone-landscape
  %a#search-toggle{:href => "#"}
    %i.fa.fa-search
  %li.dropdown
    %a#messages.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :title => "Messages"}
      %i.fa.fa-comments
    %ul#messages-menu.dropdown-menu.messages{:role => "menu"}
      %li{:role => "presentation"}
        %a.message{:href => "#"}
          %img{:alt => "", :src => "http://demo.flatlogic.com/3.2/white/img/1.jpg"}/
          .details
            .sender Jane Hew
            .text
              Hey, John! How is it going? ...
      %li{:role => "presentation"}
        %a.message{:href => "#"}
          %img{:alt => "", :src => "http://demo.flatlogic.com/3.2/white/img/2.jpg"}/
          .details
            .sender Alies Rumiancaŭ
            .text
              I'll definitely buy this template
      %li{:role => "presentation"}
        %a.message{:href => "#"}
          %img{:alt => "", :src => "http://demo.flatlogic.com/3.2/white/img/3.jpg"}/
          .details
            .sender Michał Rumiancaŭ
            .text
              Is it really Lore ipsum? Lore ...
      %li{:role => "presentation"}
        %a.text-align-center.see-all{:href => "#"}
          See all messages
          %i.fa.fa-arrow-right



  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :title => "8 support tickets"}
      %i.fa.fa-group
      %span.count 8
    %ul#support-menu.dropdown-menu.support{:role => "menu"}
      %li{:role => "presentation"}
        %a.support-ticket{:href => "#"}
          .picture
            %span.label.label-important
              %i.fa.fa-bell-o
          .details
            Check out this awesome ticket
      %li{:role => "presentation"}
        %a.support-ticket{:href => "#"}
          .picture
            %span.label.label-warning
              %i.fa.fa-question-circle
          .details
            "What is the best way to get ...
      %li{:role => "presentation"}
        %a.support-ticket{:href => "#"}
          .picture
            %span.label.label-success
              %i.fa.fa-tag
          .details
            This is just a simple notification
      %li{:role => "presentation"}
        %a.support-ticket{:href => "#"}
          .picture
            %span.label.label-info
              %i.fa.fa-info-circle
          .details
            12 new orders has arrived today
      %li{:role => "presentation"}
        %a.support-ticket{:href => "#"}
          .picture
            %span.label.label-important
              %i.fa.fa-plus
          .details
            One more thing that just happened
      %li{:role => "presentation"}
        %a.text-align-center.see-all{:href => "#"}
          See all tickets
          %i.fa.fa-arrow-right

app/views/shared/_modal_branch.haml
#modal_branch.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "#modal_branch", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:400px; z-index: 9999999999;"}
    = form_for Branch.new, url: {action: "create_branch"}, method: 'post' do |f|
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#modal_branch.modal-title
        .modal-body

          .form-group
            = f.label :short_name, "Сокращенное название филиала"
            = f.text_field :short_name, class: "form-control"
          .form-group
            = f.label :full_name, "Полное название филиала"
            = f.text_field :full_name, class: "form-control"
          .form-group
            = f.label :senior_phone, "Контактный телефон"
            = f.text_field :senior_phone, class: "form-control"
          .form-group
            = f.label :address, "Почтовый адрес"
            = f.text_field :address, class: "form-control"
            = f.hidden_field :organization_id, :value => org_id
          .form-group
            = f.submit "добавить филиал", class: "btn btn-primary"

app/views/shared/_modal_department.haml
#modal_department.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "#modal_department", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:400px; z-index: 9999999999;"}
    = form_for BranchesDepartment.new, url: {action: "create_department"}, method: 'post' do |f|
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#modal_office.modal-title
        .modal-body
          .form-group
            = f.label :branch_id, "Выберите филиал(организацию, если нет филиалов)"
            = f.select :branch_id, options_from_collection_for_select(find_branches,  "id", "short_name")
          .form-group
            = f.label :department_id, "Выберите отдел для добавления"
            = f.select :department_id, options_from_collection_for_select(Department.all, "id", "name")
          .form-group
            = f.submit "добавить филиал"

app/views/shared/_modal_enter.haml
#myModalEnter.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:350px; z-index: 999999;"}
    = form_tag new_user_session_path do
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Авторизация

        .modal-body
          = form_tag new_user_session_path, method: :post, class: "well form-horizontal"  do
            %fieldset
              .form-group
                %label{:for => "login"} Логин
                .input-group
                  %span.input-group-addon
                    %i.fa.fa-user
                  = text_field_tag 'user[username]', nil,{:class => "email form-control input-lg", placeholder: "Логин", :autofocus => true}
              .form-group
                %label{:for => "password"} Пароль
                .input-group.input-group-lg
                  %span.input-group-addon
                    %i.fa.fa-lock
                  = password_field_tag 'user[password]', nil,{:class => "password input-lg form-control", placeholder: "Пароль"}
              -#.form-group
              -#  .checkbox
              -#    %label
              -#      = check_box_tag 'user[remember_me]', nil, class: "form-control"
              -#      Запомнить в системе

            .form-actions
              %button.btn.btn-block.btn-lg.btn-danger{:type => "submit"}
                %span.small-circle
                  %i.fa.fa-caret-right
                %small Войти

app/views/shared/_modal_forum_post.haml
#modal_forum_post.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:500px; z-index: 999999;"}
    = form_for Post.new, url: {action: "create"} do |f|
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"}
          %h4#modal_forum_post.modal-title Создание темы форума
        .modal-body
          .form-group
            = f.label :title, "Название"
            %br
            = f.text_field :title, prompt: "Название темы", class: "form-control"
            %br
          .form-group
            = f.label :body, "Описание"
            %br
            = f.text_area :body, :value => params[:body], class: 'form-control', :rows => "3", prompt: "Описание темы"

            = f.hidden_field :user_id, :value => current_user.id
          = f.submit "Сохранить", class: 'btn btn-sm btn-primary', id: 'save_post'
          = link_to "Закрыть", forums_path, class: "btn btn-sm btn-default", data: { confirm: "Точно выйти?"}

app/views/shared/_modal_office.haml
#modal_office.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "#modal_office", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:400px; z-index: 9999999999;"}
    = form_tag(office_park_equipments_path,method: 'get')
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#modal_office.modal-title
      .modal-body
        = label_tag :branch_id, "Выберите филиал"
        = select_tag :branch, options_from_collection_for_select(find_branches, :id, :short_name)
        -#= f.label :dep, "Выберите отдел:", id: "label_dep"
        = grouped_collection_select(:department, :branch_id, find_branches, :departments, :short_name, :id, :name)
        -#= f.label :number, "Номер кабинета"
        = text_field_tag :number
        -#= f.label :floor
        = text_field_tag :floor
        -#= f.label :block, "Корпус"
        = text_field_tag :block
        = submit_tag "добавить кабинет"

app/views/shared/_modal_official.haml
#modal_official.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 100px; width:400px; z-index: 9999999999;"}
    .modal-content
      = form_tag(url: official_park_equipments_path, :method => 'get')
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#modal_office.modal-title
      .modal-body
        .form-group
          = label_tag :surname, "Фамилия:"
          = text_field_tag :surname, nil, class: "form-control"
          = label_tag :name, "Имя:"
          = text_field_tag :name, nil, class: "form-control"
          = label_tag :patronymic, "Отчество:"
          = text_field_tag :patronymic, nil, class: "form-control"
          = label_tag :phone, "Телефон:"
          = phone_field_tag :phone, nil, class: "form-control"
          = label_tag :branch, "Филиал"
          = select_tag :branch_id, options_from_collection_for_select(get_branches, "id", "short_name"), class: "form-control"
          = label_tag :department, "Отдел"
          = select_tag :department_id, options_from_collection_for_select(get_departments(((params[:branch_id].to_s).to_i)), "id", "name"), class: "form-control"
          %br
          = submit_tag "Сохранить", class: "btn btn-primary"

app/views/shared/_sidebar.haml
.logo
  .row
    .col-md-12
      = link_to image_tag('mednet_white.png', style: "width: 210px;"), root_path
%nav#sidebar.sidebar.nav-collapse.collapse
  %ul#side-nav.side-nav
    %li.active
      = link_to root_path do
        %i.fa.fa-home
        %span.name Главная
    %li.panel
      %ul
        %li
          = link_to root_path do
            %i.fa.fa-comments
            Форум
        %li
          = link_to root_path do
            %i.fa.fa-calendar
            Календарь задач
        %li
          = link_to park_equipments_path do
            %i.fa.fa-book
            Парк оборудования
        %li
          = link_to root_path do
            %i.fa.fa-book
            Банк документов
    %li.panel
      %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#stats-collapse"}
        %i.fa.fa-bar-chart
        %span.name Статистика
      %ul#stats-collapse.panel-collapse.collapse
        %li
          %a{:href => "stat_statistics.html"} Мониторинг
        %li
          %a{:href => "stat_charts.html"} Графики
        %li
          %a{:href => "stat_realtime.html"} Статистическая информация
    %li.panel
      %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#reports-collapse"}
        %i.fa.fa-briefcase
        %span.name Отчетность
      %ul#reports-collapse.panel-collapse.collapse
        %li
          %a{:href => "stat_statistics.html"} Отчетность по календарю
        %li
          %a{:href => "stat_charts.html"} Дополнительная информация
    %li.panel
      %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#vpch-collapse"}
        %i.fa.fa-medkit
        %span.name ВПЧ-скрининг
      %ul#vpch-collapse.panel-collapse.collapse
        %li
          = link_to "Поиск пациента", root_path
        %li
          = link_to "Мои пациенты", root_path
        %li
          = link_to "Реестры", root_path
        %li
          = link_to "Справочники", root_path
        %li
          = link_to "Лабораторные исследования", root_path
        %li
          = link_to "Отчетность", root_path
        %li
          = link_to "Дополнительные функции", root_path

    %li.panel
      %ul
        %li
          = link_to root_path do
            %i.fa.fa-university
            Инструкции
        %li
          = link_to root_path do
            %i.fa.fa-envelope
            Контакты

  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#forms-collapse"}
  -#      %i.fa.fa-pencil
  -#      %span.name Forms
  -#    %ul#forms-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "form_account.html"} Account
  -#      %li
  -#        %a{:href => "form_article.html"} Article
  -#      %li
  -#        %a{:href => "form_elements.html"} Elements
  -#      %li
  -#        %a{:href => "form_validation.html"} Validation
  -#      %li
  -#        %a{:href => "form_wizard.html"} Wizard
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#stats-collapse"}
  -#      %i.fa.fa-area-chart
  -#      %span.name Statistics
  -#    %ul#stats-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "stat_statistics.html"} Stats
  -#      %li
  -#        %a{:href => "stat_charts.html"} Charts
  -#      %li
  -#        %a{:href => "stat_realtime.html"} Realtime
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#ui-collapse"}
  -#      %i.fa.fa-magic
  -#      %span.name User Interface
  -#    %ul#ui-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "ui_buttons.html"} Buttons
  -#      %li
  -#        %a{:href => "ui_dialogs.html"} Dialogs
  -#      %li
  -#        %a{:href => "ui_notifications.html"} Notifications
  -#      %li
  -#        %a{:href => "ui_icons.html"} Icons
  -#      %li
  -#        %a{:href => "ui_tabs.html"} Tabs
  -#      %li
  -#        %a{:href => "ui_accordion.html"} Accordion
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#components-collapse"}
  -#      %i.fa.fa-tree
  -#      %span.name Components
  -#    %ul#components-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "component_calendar.html"} Calendar
  -#      %li
  -#        %a{"data-no-pjax" => "", :href => "component_maps.html"} Maps
  -#      %li
  -#        %a{:href => "component_gallery.html"} Gallery
  -#      %li
  -#        %a{"data-no-pjax" => "", :href => "component_fileupload.html"} Fileupload
  -#      %li
  -#        %a{:href => "component_bootstrap.html"} Bootstrap
  -#      %li
  -#        %a{:href => "component_list_groups.html"} List Groups
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#tables-collapse"}
  -#      %i.fa.fa-cog
  -#      %span.name Tables
  -#    %ul#tables-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "tables_static.html"}
  -#          Static
  -#          %sup.text-danger.fw-bold upd
  -#      %li
  -#        %a{:href => "tables_dynamic.html"} Dynamic
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#grid-collapse"}
  -#      %i.fa.fa-th
  -#      %span.name Widgets
  -#    %ul#grid-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "grid_basic.html"} Basic
  -#      %li
  -#        %a{:href => "grid_live.html"} Live
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#special-collapse"}
  -#      %i.fa.fa-leaf
  -#      %span.name Special
  -#    %ul#special-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "special_search.html"}
  -#          Search
  -#          %sup.text-warning.fw-bold new
  -#      %li
  -#        %a{:href => "special_invoice.html"} Invoice
  -#      %li
  -#        %a{:href => "special_inbox.html"}
  -#          Inbox  
  -#          %span.label.label-important 3
  -#      %li
  -#        %a{:href => "login.html", :target => "_blank"} Login
  -#      %li
  -#        %a{:href => "error.html", :target => "_blank"} Error Page
  -#      %li
  -#        %a{"data-no-pjax" => "", :href => "../transparent/landing.html"} Landing
  -#      %li
  -#        %a{"data-no-pjax" => "", :href => "../transparent/index.html"} Transparent
  -#  %li.panel
  -#    %a.accordion-toggle.collapsed{"data-parent" => "#side-nav", "data-toggle" => "collapse", :href => "#menu-levels-collapse"}
  -#      %i.fa.fa-folder-open
  -#      %span.name Menu Levels
  -#    %ul#menu-levels-collapse.panel-collapse.collapse
  -#      %li
  -#        %a{:href => "#"} Item 1.1
  -#      %li
  -#        %a{:href => "#"} Item 1.2
  -#      %li.panel
  -#        %a.accordion-toggle.collapsed{"data-parent" => "#menu-levels-collapse", "data-toggle" => "collapse", :href => "#sub-menu-1-collapse"} Item 1.3
  -#        %ul#sub-menu-1-collapse.panel-collapse.collapse
  -#          %li.panel
  -#            %a.accordion-toggle.collapsed{"data-parent" => "#sub-menu-1-collapse", "data-toggle" => "collapse", :href => "#sub-menu-3-collapse"} Item 2.1
  -#            %ul#sub-menu-3-collapse.panel-collapse.collapse
  -#              %li
  -#                %a{:href => "#"} Item 3.1
  -#              %li
  -#                %a{:href => "#"} Item 3.2
  -#              %li
  -#                %a{:href => "#"} Item 3.3
  -#          %li
  -#            %a{:href => "#"} Item 2.2
  -#          %li.panel
  -#            %a.accordion-toggle.collapsed{"data-parent" => "#sub-menu-1-collapse", "data-toggle" => "collapse", :href => "#sub-menu-2-collapse"} Item 2.3
  -#            %ul#sub-menu-2-collapse.panel-collapse.collapse
  -#              %li
  -#                %a{:href => "#"} Item 3.4
  -#              %li
  -#                %a{:href => "#"} Item 3.5
  -#              %li
  -#                %a{:href => "#"} Item 3.6
  -#  %li.visible-xs
  -#    %a{:href => "login.html"}
  -#      %i.fa.fa-sign-out
  -#      %span.name Sign Out
  -#%h5.sidebar-nav-title
  -#  Labels
  -#  %a.action-link{:href => "#"}
  -#    %i.glyphicon.glyphicon-plus
  -#/ some styled links in sidebar. ready to use as links to email folders, projects, groups, etc
  -#%ul.sidebar-labels
  -#  %li
  -#    %a{:href => "#"}
  -#      / yep, .circle again
  -#      %i.fa.fa-circle.text-warning
  -#      %span.label-name My Recent
  -#  %li
  -#    %a{:href => "#"}
  -#      %i.fa.fa-circle.text-gray
  -#      %span.label-name Starred
  -#  %li
  -#    %a{:href => "#"}
  -#      %i.fa.fa-circle.text-danger
  -#      %span.label-name Background
  -#%h5.sidebar-nav-title Projects
  -#/ A place for sidebar notifications & alerts
  .sidebar-alerts
    .alert.fade.in
      %a.close{"aria-hidden" => "true", "data-dismiss" => "alert", :href => "#"} ×
      %span.text-white.fw-semi-bold Пациенты не в реестре
      %br/
      .progress.progress-xs.mt-xs.mb-0
        .progress-bar.progress-bar-gray-light{:style => "width: 16%"}
      %small 65 чел.
    -#.alert.fade.in
    -#  %a.close{"aria-hidden" => "true", "data-dismiss" => "alert", :href => "#"} ×
    -#  %span.text-white.fw-semi-bold Personal Responsibility
    -#  %br/
    -#  .progress.progress-xs.mt-xs.mb-0
    -#    .progress-bar.progress-bar-danger{:style => "width: 23%"}
    -#  %small Provide required notes

app/views/shared/_topbar.haml
%header.page-header
  .navbar
    %ul.nav.navbar-nav.navbar-right.pull-right
      - if user_signed_in?
        = render 'shared/all_icons_user'
        %li.divider

        %li.hidden-xs.dropdown
          -#%a#account.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :title => "Account"}
          %button.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", :title => "Account", "data-toggle" => "dropdown", :type => "button"}
            -#= current_user.fio
            %i.fa.fa-user
            = current_user.fio
          %ul#account-menu.dropdown-menu.account{:role => "menu"}
            -#%li.account-picture{:role => "presentation"}
            -#  %img{:alt => "", :src => "http://demo.flatlogic.com/3.2/white/img/2.jpg"}/
            -#  Philip Daineka
            %li{:role => "presentation"}
              %a.link{:href => "form_account.html"}
                %i.fa.fa-user
                Profile
            %li{:role => "presentation"}
              %a.link{:href => "component_calendar.html"}
                %i.fa.fa-calendar
                Calendar
            %li{:role => "presentation"}
              %a.link{:href => "#"}
                %i.fa.fa-inbox
                Inbox

            - if current_user.has_role? :admin
              %li{:role => "presentation"}
                = link_to admin_park_equipments_path do
                  %i.fa.fa-inbox
                  Справочники
            %li{:role => "presentation"}
              = link_to destroy_user_session_path, :method => :delete do
                %i.fa.fa-sign-out
                Выход


        -#%li
        -#= link_to destroy_user_session_path, :method => :delete, class: "btn btn-danger" do
        -#  %i.fa.fa-sign-out
        -#  Выход

      - else

        = link_to "#", class: "btn btn-primary", "data-target" => "#myModalEnter", "data-toggle" => "modal" do
          %i.fa.fa-user.fa-lg
          Вход в систему
        %li.divider




    -#нотификация
    -#.notifications.pull-right
      -#.alert.pull-right
      -#  %a.close.ml-xs{"data-dismiss" => "alert", :href => "#"} ×
      -#  %i.fa.fa-info-circle.mr-xs
      -#  Check out Light Blue
      -#  %a#notification-link{:href => "#"} settings
      -#  on the right!