config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
<<<<<<< HEAD

=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
  devise_for :users

  resources :park_equipments, :only => :index do
    collection do
      get 'office'
      post 'office'
      post 'search_dep'
<<<<<<< HEAD
<<<<<<< HEAD
      get 'official'
      post 'official'
=======
=======
>>>>>>> origin/Klavakurochkina
      post 'create_branch'
      get 'create_branch'
      post 'create_department'
      get 'search_office'
      post 'search_office'
      get 'add_office'
      get 'delete_office'
<<<<<<< HEAD
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
<<<<<<< HEAD

>>>>>>> origin/Klavakurochkina
=======
>>>>>>> origin/Klavakurochkina
=======
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
>>>>>>> origin/Klavakurochkina
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
    end
  end

end

app/controllers/park_equipments_controller.rb
class ParkEquipmentsController < ApplicationController

  before_filter :user_present
  def user_present
    unless current_user.present?
      redirect_to root_path, notice: "Чтобы войти в подсистему, авторизуйтесь!"
    end
  end


  def index

  end
  def official
    Octopus.using(:shard_one) do
      # @official=Official.new
      # render text: Official.official_branch_show(1)
      # if params[:branch_id].present?
      #   render text: params.inspect
      # end

      # if params[:commit].present?
      #   # Official.official_add(params)
      #   # render text: params[:branch_id].to_s.to_i
      #   # flash[:]
      # end

    end
    if params[:commit].present?
      render text: params[:branch_id].to_s.to_i.class
    end


  end

  def office
    @org = Organization.find(Userinfo.find_by_user_id(current_user.id).organization_id)
    @departments_all = Department.all
    @department = Department.find(params[:department_id]) if params[:department_id].present?
    if params[:commit] == "филиалов нет"
      @branch = Branch.add_branch(params)
      if @branch.errors.present?
        flash[:danger] = "Ошибки при заполнении формы"
      end
      redirect_to office_park_equipments_path
    end
  end


  def search_office
    @offices = []
    if params[:commit].present?
      # render text: params.inspect
      @offices = Office.office_search(params)
      render 'search_office'
    end
  end


  def show_office
    @office = Office.using(:shard_one).find(params[:id])
    br_dep_id = @office.branches_department_id
    br_dep = BranchesDepartment.find(br_dep_id)
    @branch = Branch.find(br_dep.branch_id)
    @department = Department.find(br_dep.department_id)
  end

  def create_branch
    if params[:commit] == 'добавить филиал'
        @branch = Branch.create(branch_params)
        flash[:success] = "Запись для филиала создана"
        # render text: params.inspect
        if @branch.errors.present?
          flash[:danger] = "Ошибки при заполнении формы"
        end
       redirect_to office_park_equipments_path
    end
  end

  def show_branch
    @branch = Branch.find(params[:id])
  end
  respond_to :html, :json

  def edit_branch
    @branch = Branch.find(params[:id])
    respond_to do |format|
      if @branch.update_attributes(branch_params)
        format.html { redirect_to(@branch) }
        format.json { respond_with_bip(@branch) }
      else
        format.html { render :action => "edit_branch" }
        format.json { respond_with_bip(@branch) }
      end
    end
  end

  def create_department
    if params[:commit].present?
      @branch_department = BranchesDepartment.create(branches_department_params)
      flash[:success] = "Запись связки создана"
      # render text: params.inspect
      if @branch_department.errors.present?
        flash[:danger] = "Ошибки при заполнении формы"
      end
    end
    redirect_to office_park_equipments_path
  end

  def create_department
    if params[:commit].present?
      @branch_department = BranchesDepartment.create(branches_department_params)
      flash[:success] = "Запись связки создана"
      # render text: params.inspect
      if @branch_department.errors.present?
        flash[:danger] = "Ошибки при заполнении формы"
      end
    end
    redirect_to office_park_equipments_path
  end

  def add_office
    @office = Office.using(:shard_one).new
    @branch_id = Branch.new
    if params[:commit] == 'сохранить кабинет'
      department_id = params.require(:department).require(:branch_id).to_i
      @bra_dep = BranchesDepartment.where(branch_id: params[:branch],department_id: department_id).first
      @office = Office.using(:shard_one).create(branches_department_id: @bra_dep.id, number: params[:number],
          floor: params[:floor], block: params[:block], is_deleted: false)
      flash[:success] = "Запись для кабинета создана"
      if @office.errors.present?
        flash[:danger] = "Ошибки при заполнении формы кабинета"
      end
      redirect_to office_park_equipments_path
    end
  end

  def delete_office
    @office = Office.using(:shard_one).find(params[:id])
    @office.update_attributes!(id: params[:id], is_deleted: true)
    redirect_to office_park_equipments_path
  end

  def edit_office
    @office = Office.using(:shard_one).find(params[:id])
    @office_br_dep_id = @office.branches_department_id
    @branch_id = BranchesDepartment.find(@office_br_dep_id).branch_id
    @department_id = BranchesDepartment.find(@office_br_dep_id).department_id
    if params[:commit] == 'сохранить кабинет'
      department_id = params.require(:department).require(:branch_id).to_i
      if BranchesDepartment.where(branch_id: params[:branch],department_id: department_id).first.present?
        @bra_dep = BranchesDepartment.where(branch_id: params[:branch],department_id: department_id).first
        @office = @office.update_attributes!(branches_department_id: @bra_dep.id, number: params[:number],
                                             floor: params[:floor], block: params[:block], is_deleted: false)
        flash[:success] = "Запись для кабинета обновлена"
      else
        flash[:danger] = "Проверьте заданные параметры. Для вашей организации не задано такого сочетания филиала и отдела"
      end
      redirect_to office_park_equipments_path
    end

  end


  private
    def office_params
      params.require(:office).permit!
    end
    def official_params
      params.require(:official).permit!
    end
    def branch_params
      params.require(:branch).permit!
    end

    def branches_department_params
      params.require(:branches_department).permit!
    end


end

app/helpers/park_equipments_helper.rb
module ParkEquipmentsHelper
  def set_organization user_id
    org_id = Userinfo.find_by_user_id(user_id).organization_id
    org_name = Organization.find(org_id).short_name
    return org_name
  end

  def org_id
    org_id = Userinfo.find_by_user_id(current_user.id).organization_id
    return org_id
  end

<<<<<<< HEAD
<<<<<<< HEAD
  def get_branches
    Branch.where(organization_id: Organization.find(Userinfo.find_by_user_id(current_user.id).organization_id).id)
  end

  def get_departments branch_id
    i=rand(1)+1
      Department.where(id: BranchesDepartment.where(branch_id: i))
  end


  # def select_department branch_id
  #
  #   dep_id = BranchesDepartment.where(branch_id: branch_id)
  #   i = 0
  #   dep_id_arr = []
  #   while (i < dep_id.count) do
  #     dep_id_arr[i]=dep_id.find(i+1).department_id
  #     i += 1
  #   end
  #
  #   @departments = Department.find(dep_id_arr)
  #
  #   return @departments
  #
  #
  # end

  def branch_exist org_id
=======
=======
>>>>>>> origin/Klavakurochkina
  def find_branches
    orgid= Userinfo.find_by_user_id(current_user.id).organization_id
    @branches = Branch.where(organization_id: orgid)
    return @branches
  end


  def branch_only_one org_id
<<<<<<< HEAD
>>>>>>> origin/Klavakurochkina
=======
>>>>>>> origin/Klavakurochkina
    branch = Branch.find_by_organization_id(org_id)
    if branch.present?
      if branch.full_name == Organization.find(branch.organization_id).full_name and
         branch.short_name == Organization.find(branch.organization_id).short_name and
          branch.address == Organization.find(branch.organization_id).address
        return true
      else
        return false
      end
<<<<<<< HEAD
=======
    end
  end

  def find_departments_no_branches

    branch_id = Branch.find_by_organization_id(org_id).id
    find_departments(branch_id)
  end


  def find_departments branch_id
    departments = BranchesDepartment.where(branch_id: branch_id)
    dep_id_arr = []
    departments.each do |dep|
      dep_id_arr << dep.department_id
    end
    @departments = Department.find(dep_id_arr)
    return @departments
  end

  def find_offices branch_id, department_id
    br_dep_id = BranchesDepartment.where(branch_id: branch_id, department_id: department_id)

    br_dep_id_ar = []
    br_dep_id.each do |id|
      br_dep_id_ar << id.id
>>>>>>> origin/Klavakurochkina
    end
    @offices = Office.using(:shard_one).where(branches_department_id: br_dep_id_ar, is_deleted: false)
    return @offices
  end

  def find_departments_no_branches

    branch_id = Branch.find_by_organization_id(org_id).id
    find_departments(branch_id)
  end


  def find_departments branch_id
    departments = BranchesDepartment.where(branch_id: branch_id)
    dep_id_arr = []
    departments.each do |dep|
      dep_id_arr << dep.department_id
    end
    @departments = Department.find(dep_id_arr)
    return @departments
  end

  def find_offices branch_id, department_id
    br_dep_id = BranchesDepartment.where(branch_id: branch_id, department_id: department_id)

    br_dep_id_ar = []
    br_dep_id.each do |id|
      br_dep_id_ar << id.id
    end
    @offices = Office.using(:shard_one).where(branches_department_id: br_dep_id_ar, is_deleted: false)
    return @offices
  end
end

app/views/park_equipments/_menu.haml
.well
  .navbar-collapse.collapse
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Кабинеты
          %b.caret
        %ul.dropdown-menu
          -#%li.divider
          -#%li.dropdown-header Кабинеты
          %li
            =link_to "Список кабинетов организации", office_park_equipments_path
          %li
            =link_to "Добавить кабинет", add_office_park_equipments_path
            -#%a{:href => "#"} Создать кабинет
          %li
            = link_to "Поиск по кабинетам", search_office_park_equipments_path
      %li
        %a{:href => "#"} Создать конфигурацию оборудования
      %li
        %a{:href => "#"} Link
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          Справочники
          %b.caret
        %ul.dropdown-menu
          %li.divider
          %li.dropdown-header Организация
          %li
            %a{:href => "#"} Отделы
          %li
            %a{:href => "#"} Должности
          %li.divider
          %li.dropdown-header Оборудование
          %li
            %a{:href => "#"} Производители
          %li
            %a{:href => "#"} Модели
    %ul.nav.navbar-nav.navbar-right
      %li.active
        %a{:href => "./"} Выбрать склад (На склад появится, если склад определен)
      %li
        %a{:href => "../navbar-static-top/"} что-то еще
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          = set_organization(current_user.id)
          %b.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#"} Отделы(для данной организации)
          %li
            = link_to "Ответственные", official_park_equipments_path

app/views/park_equipments/_office.haml
.form-control
  = label_tag :branch_id, "Выберите филиал"
  = select_tag :branch, options_from_collection_for_select(find_branches, :id, :short_name, @branch_id)
  = label_tag :dep, "Выберите отдел:", id: "label_dep"
  = grouped_collection_select(:department, :branch_id, find_branches, :departments, :short_name, :id, :name)

  .form-inline
    .form-group
      = label_tag :number, "Номер кабинета"
      %br
      = text_field_tag :number, @office.number, class: "form-control"
    .form-group
      = label_tag :floor, "Этаж"
      %br
      = text_field_tag :floor, @office.floor, class: "form-control"
    .form-group
      = label_tag :block, "Корпус"
      %br
      = text_field_tag :block, @office.block, class: "form-control"
  = submit_tag "сохранить кабинет", class: "btn btn-primary"

app/views/park_equipments/add_office.haml
= render 'menu'
%strong
  .text-center
    Создание записи о кабинете
.form-group
  = form_tag(add_office_park_equipments_path, method: 'get') do
    = render 'office'

app/views/park_equipments/edit_branch.haml
= render 'menu'
= form_for @branch, url: {action: "edit_branch"}, method: 'get' do |f|
  .form-group
    = f.label :short_name, "Сокращенное название филиала"
    = f.text_field :short_name, class: "form-control"
  .form-group
    = f.label :full_name, "Полное название филиала"
    = f.text_field :full_name, class: "form-control"
  .form-group
    = f.label :senior_phone, "Контактный телефон"
    = f.text_field :senior_phone, class: "form-control"
  .form-group
    = f.label :address, "Почтовый адрес"
    = f.text_field :address, class: "form-control"
    = f.hidden_field :organization_id, :value => org_id
  .form-group
    = f.submit "изменить филиал", class: "btn btn-primary"

app/views/park_equipments/edit_office.haml
= render 'menu'
%strong
  .text-center
    Редактирование записи кабинета
.form-group
  = form_tag(edit_office_park_equipment_path, method: 'get') do
    = render "office"

app/views/park_equipments/index.haml
= render 'menu'
= render 'shared/modal_office'

.jumbotron
  %h1 Навигационное меню
  %p
    шаблон



    -#= link_to "Создать новый кабинет", "", "data-target" => "#modal_office", "data-toggle" => "modal", class: "btn btn-success btn-sm"

app/views/park_equipments/office.haml
= render 'menu'

= render 'shared/modal_branch'
= render 'shared/modal_department'

%br
-if find_branches.present?
  -unless branch_only_one(org_id)
    %p{:align => "right"}
      = link_to "добавить филиал", "#modal_branch", class: "btn btn-primary", "data-toggle" => "modal"

      = link_to "добавить отдел", "#modal_department",class: "btn btn-primary", "data-toggle" => "modal"

      = link_to "добавить кабинет", add_office_park_equipments_path, class: "btn btn-primary"
      %br

    %h3
      %center
        Структура учреждения  #{set_organization(current_user.id)}
    %br
    .well
      .field_input
        -find_branches.each do |branch|
          Филиал: #{branch.short_name}
          =link_to show_branch_park_equipment_path(id: branch.id), class: "btn btn-sm btn-success" do
            %i.fa.fa.fa-search-plus
          %br
          .well
            -find_departments(branch.id).each do |department|
              =department.name
              %br
              .well
                -if find_offices(branch.id, department.id).present?
                  %table.table.active
                    %tr.info
                      %th Номер кабинета
                      %th Корпус
                      %th Этаж
                      %th Редакция
                    %tbody

                      -find_offices(branch.id, department.id).each do |office|
                        %tr
                          %td
                            =link_to  "#{office.number}", show_office_park_equipment_path(office.id)
                          %td
                            =office.block
                          %td
                            =office.floor
                          %td
                            = link_to edit_office_park_equipment_path(id: office.id), class: "btn btn-sm btn-warning" do
                              %i.fa.fa.fa-pencil-square-o

                            = link_to delete_office_park_equipments_path(id: office.id), data: { confirm: "Точно удалить?"}, class: "btn btn-sm btn-danger" do
                              %i.fa.fa.fa-trash-o

                            =link_to show_office_park_equipment_path(id: office.id), class: "btn btn-sm btn-success" do
                              %i.fa.fa.fa-search-plus


                -else
                  Кабинетов нет

  -else
    Создавайте отделы и кабинеты для вашей организации
    %p{:align => "right"}
      = link_to "добавить отдел", "#modal_department",class: "btn btn-primary", "data-toggle" => "modal"

      = link_to "добавить кабинет", add_office_park_equipments_path, class: "btn btn-primary"
      %br
    .well
      .field_input
        -if find_departments_no_branches.present?
          -find_departments_no_branches.each do |department|
            =department.name
            %br
            .well
              -if find_offices(Branch.find_by_organization_id(org_id).id, department.id).present?
                %table.table.active
                  %tr.info
                    %th Номер кабинета
                    %th Корпус
                    %th Этаж
                    %th Редакция
                  %tbody

                    -find_offices(Branch.find_by_organization_id(org_id).id, department.id).each do |office|
                      %tr
                        %td
                          =link_to  "#{office.number}", show_office_park_equipment_path(office.id)
                        %td
                          =office.block
                        %td
                          =office.floor
                        %td
                          = link_to edit_office_park_equipment_path(id: office.id), class: "btn btn-sm btn-warning" do
                            %i.fa.fa.fa-pencil-square-o

                          = link_to delete_office_park_equipments_path(id: office.id), data: { confirm: "Точно удалить?"}, class: "btn btn-sm btn-danger" do
                            %i.fa.fa.fa-trash-o

                          =link_to show_office_park_equipment_path(id: office.id), class: "btn btn-sm btn-success" do
                            %i.fa.fa.fa-search-plus


              -else
                Кабинетов нет
        - else
          Отделов нет
-else
  Пока не создано ни одного филиала для вашей организации.
  %br
  Если у вашей организации нет филиалов, нажмите кнопку
  =link_to "Филиалов не существует", office_park_equipments_path(commit: "филиалов нет",
  organization_id: org_id,  short_name: Organization.find(org_id).short_name,
  full_name:  Organization.find(org_id).full_name, senior_phone: Organization.find(org_id).reception_phone,
  address: Organization.find(org_id).address), class: "btn btn-primary", data: { confirm: "Точно нет филиалов?"}
  %br
  Если  в вашей организации присутствуют филиалы, то их можно задать, нажав кнопку
  = link_to "добавить филиал", "#modal_branch", class: "btn btn-primary", "data-toggle" => "modal"
%br

app/views/park_equipments/official.haml
=render 'shared/modal_official'
=render 'menu'
= link_to "#", class: "btn btn-primary", "data-target" => "#modal_official", "data-toggle" => "modal"  do
  Добавить ответственного
-#= form_tag(park_equipments_official_path, :method => 'post') do
-#  .form-group
    -#.row
    -#  .col
    -#    = label_tag :surname, "Фамилия:"
    -#    = text_field_tag :surname, "Фамилия"
    -#.row
    -#  .col
    -#    = label_tag :name, "Имя:"
    -#    = text_field_tag :name, "Имя:"
    -#.row
    -#  .col
    -#    = label_tag :patronymic, "Отчество:"
    -#    = text_field_tag :patronymic, "Отчество:"
    -#%table
    -#  %tr
    -#    %td
    -#      = label_tag :surname, "Фамилия:"
    -#    %td
    -#      = text_field_tag :surname
    -#  %tr
    -#    %td
    -#      = label_tag :name, "Имя:"
    -#    %td
    -#      = text_field_tag :name
    -#  %tr
    -#    %td
    -#      = label_tag :patronymic, "Отчество:"
    -#    %td
    -#      = text_field_tag :patronymic
    -#  %tr
    -#    %td
    -#      = label_tag :phone, "Телефон:"
    -#    %td
    -#      = phone_field_tag :phone
    -#  %tr
    -#    %td
    -#      = label_tag :branch, "Филиал"
    -#    %td
    -#      = select_tag :branch_id, "<option>1</option><option>2</option><option>3</option><option>4</option>".html_safe, class: "form-control"
    -#  %tr
    -#    %td
    -#      = label_tag :department, "Отдел"
    -#    %td
    -#      = select_tag :department_id, "<option>1</option><option>2</option><option>3</option><option>4</option>".html_safe, class: "form-control"
    -#  %tr
    -#    %td
    -#    %td
    -#      = submit_tag "Сохранить", class: "btn"

app/views/park_equipments/search_office.haml
= render 'menu'
.well
  = form_tag(search_office_park_equipments_path, method: 'post') do
    .row
      .col-md-5
        = select_tag :branch_id, options_from_collection_for_select(find_branches, "id", "short_name", params[:branch_id]), prompt: "Выберите филиал", class: "form-control"
      .col-md-5
        = select_tag :department_id, options_from_collection_for_select(Department.all, "id", "name", params[:department_id]) , prompt: "Выберите отдел", class: "form-control"

      = hidden_field_tag :org_id, org_id
      .col-md-2

        = submit_tag "Поиск", class: "btn btn-primary",data: { disable_with: "Идет поиск, подождите...".html_safe}

    .row
      .col-md-10
      .col-md-2
        .pull-right
          %br
            = link_to "Расширенный поиск", "#", {"data-target" => "#extra_search_fields", "data-toggle" => "collapse"}

    #extra_search_fields.collapsible.collapse
      %br
      .row
        .col-md-4
          = label_tag :number, "Номер или название кабинета"
          %br
          =text_field_tag :number, params[:number], placeholder: "Наименование кабинета", class: 'form-control'

          %br
        .col-md-4
          = label_tag :floor, 'Этаж'
          %br
          =text_field_tag :floor, params[:floor], placeholder: "Этаж", class: 'form-control'

          %br
        .col-md-4
          = label_tag :block, "Корпус"
          %br
          = text_field_tag :block, params[:block], placeholder: "Корпус", class: "form-control"
          %br
      .row
        .pull-right
          %i
            = link_to "Cбросить поиск", office_park_equipments_path


-if params[:commit].present? and @offices.blank?
  %center
    %h3
      Кабинетов, удовлетворяющих вашему запросу, не нашлось.


-elsif params[:commit].present? and @offices.present?

  %strong
    %h4
      Результаты поиска:   #{@offices.count} каб.
      -if @branch_name.present?
        филиал:
        #{@branch_name.short_name}
      -if @department.present?
        отдел: #{@department.name}
  %p
    .well
      .field_input
        %table.table.table-bordered
          %th.info
            Номер кабинета
            - @offices.each do |office|
              %tr
                %td{style: "width:80%;"}
                  = link_to office.number.html_safe, show_office_park_equipment_path(id: office.id)

app/views/park_equipments/show_branch.haml
= render 'menu'
%h3
  %center
    Информация о филиале
.form-group
  .well
    .field_input
      %p{:align => "right"}
        %i
          Чтобы отредактировать данные, щелкните по нужному полю
      Ваша организация:
      = set_organization(current_user.id)
      %br
      Филиал:
      =best_in_place @branch, :short_name, path: edit_branch_park_equipment_path(@branch), :place_holder => "Click me to add content!"

      %br
      Полное название:
      =best_in_place @branch, :full_name, path: edit_branch_park_equipment_path(@branch)
      %br
      Телефон:
      = best_in_place @branch, :senior_phone, path: edit_branch_park_equipment_path(@branch)
      %br
      Адрес:
      =best_in_place @branch, :address, path: edit_branch_park_equipment_path(@branch)

%p{:align => "right"}
  =link_to "Вернуться к структуре организации", office_park_equipments_path, data: {confirm: "Точно перейти?"}, class: "btn btn-sn btn-primary"
  -#=link_to "Редактировать запись", edit_branch_park_equipment_path(id: @branch.id), class: "btn btn-sn btn-primary"

app/views/park_equipments/show_office.haml
= render 'menu'
%h3
  %center
    Информация о кабинете
.form-group
  .well
    .field_input
      Ваша организация:
      = set_organization(current_user.id)
      %br
      Филиал: #{@branch.short_name}, контактный телефон: #{@branch.senior_phone}, адрес: #{@branch.address}
      %br
      Отдел: #{@department.name}
      %br
      Кабинет номер: #{@office.number}, корпус #{@office.block}, этаж #{@office.floor}


%p{:align => "right"}
  =link_to "Вернуться к структуре организации", office_park_equipments_path, data: {confirm: "Точно перейти?"}, class: "btn btn-sn btn-primary"
  =link_to "Удалить кабинет", delete_office_park_equipments_path(id: params[:id]), data: {confirm: "Точно удалить?"}, class: "btn btn-sn btn-primary"