config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
<<<<<<< HEAD

=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
=======
  root 'main#index'
>>>>>>> origin/Klavakurochkina
  devise_for :users

  resources :park_equipments, :only => :index do
    collection do
      get 'office'
      post 'office'
      post 'search_dep'
<<<<<<< HEAD
<<<<<<< HEAD
      get 'official'
      post 'official'
=======
=======
>>>>>>> origin/Klavakurochkina
      post 'create_branch'
      get 'create_branch'
      post 'create_department'
      get 'search_office'
      post 'search_office'
      get 'add_office'
      get 'delete_office'
<<<<<<< HEAD
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
<<<<<<< HEAD

>>>>>>> origin/Klavakurochkina
=======
>>>>>>> origin/Klavakurochkina
=======
    end
    member do
      get 'show_office'
      get 'edit_office'
      get 'show_branch'
      get 'edit_branch'
      put 'edit_branch'
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
>>>>>>> origin/Klavakurochkina
    end
  end

  resources :admin_park_equipments, :only => :index do
    collection do
      get 'department'
      get 'position'

      post 'create_department'
      post 'create_position'
      get 'delete_department'
      get 'delete_position'
    end
    member do
      put 'edit_department'
      put 'edit_position'
    end
  end

end

app/controllers/admin_park_equipments_controller.rb
class AdminParkEquipmentsController < ApplicationController
  before_filter :user_admin

  def user_admin
    unless current_user.has_role? :admin
      redirect_to root_path, notice: "У вас недостаточно прав, чтобы войти в подсистему"
    end
  end


  def index
    redirect_to department_admin_park_equipments_path
  end

  def department
    @departments = Department.all.order(:name)
    @department = Department.new
  end

  def create_department
    if params[:commit] == 'добавить отдел'
      @department = Department.add_department(department_params)
      if @department.errors.present?
        render 'department', notice: "Не удалось добавить запись из-за ошибки"
      else
        redirect_to department_admin_park_equipments_path, notice: "Запись добавлена"
      end
    end
  end

  def edit_department
    @department = Department.find(params[:id])
    respond_to do |format|
      if @department.update_attributes(department_params)
        format.html { redirect_to(@department) }
        format.json { respond_with_bip(@department) }
      else
        format.html { render :action => "edit_department" }
        format.json { respond_with_bip(@department) }
      end
    end
  end

  def delete_department
    @department = Department.find(params[:id])
    @department.destroy
    flash[:success] = "Запись отдела удалена"
    redirect_to department_admin_park_equipments_path
  end

  def position
    @position = Position.new
    @positions = Position.all.order(:name)
  end

  def create_position
    if params[:commit] == 'добавить должность'
      @position = Position.add_positions(position_params)
      if @position.errors.present?
        render 'position', notice: "Не удалось добавить запись из-за ошибки"
      else
        redirect_to position_admin_park_equipments_path, notice: "Запись добавлена"
      end
    end
  end

  def edit_position
    @position = Position.find(params[:id])
    respond_to do |format|
      if @position.update_attributes(position_params)
        format.html { redirect_to(@position) }
        format.json { respond_with_bip(@position) }
      else
        format.html { render :action => "edit_position" }
        format.json { respond_with_bip(@position) }
      end
    end
  end

  def delete_position
    @position = Position.find(params[:id])
    @position.destroy
    flash[:success] = "Запись должности удалена"
    redirect_to position_admin_park_equipments_path
  end



  private
  def department_params
    params.require(:department).permit!
  end

  def position_params
    params.require(:position).permit!
  end

end

app/views/admin_park_equipments/_menu.haml
%ul.nav.nav-pills
  %li
    = link_to "Отделы", department_admin_park_equipments_path
    -#%a{:href => "#"} Главная
  %li
    = link_to "Должности", position_admin_park_equipments_path




-#%nav#sidebar.sidebar.nav-collapse.collapse
  %ul#side-nav.side-nav
    %li.active
      = link_to root_path do
        %i.fa.fa-home
        %span.name Главная
    %li.panel
      %ul
        %li
          = link_to root_path do
            %i.fa.fa-comments
            Форум
        %li
          = link_to root_path do
            %i.fa.fa-calendar
            Календарь задач
        %li
          = link_to park_equipments_path do
            %i.fa.fa-book
            Парк оборудования
        %li
          = link_to root_path do
            %i.fa.fa-book
            Банк документов

            -#.navbar-collapse.collapse

app/views/admin_park_equipments/department.haml
.well-sm
  %h2
    %center Администрирование справочника отделов
=render 'menu'
.well
  .field_input
    %p{:align => "left"}
      %i
        Чтобы отредактировать данные, щелкните по нужной записи
    - if @departments.present?
      %table.table.table-editable
        -@departments.each do |department|
          %tr
            %td
              =best_in_place department, :name, path: edit_department_admin_park_equipment_path(department.id)
            %td
              = link_to delete_department_admin_park_equipments_path(id: department.id), data: { confirm: "Точно удалить?"}, class: "btn btn-sm btn-danger" do
                %i.fa.fa.fa-trash-o


.well
  .field_input
    =form_for(@department, url: create_department_admin_park_equipments_path) do |f|
      = f.label :name, "Название отдела", class: "form-control"
      = f.text_field :name, class: "form-control"
      = f.submit "добавить отдел", class: "btn btn-sm btn-primary"

app/views/admin_park_equipments/index.haml
.well-sm
  %h2
    %center Администрирование справочников
=render 'menu'

app/views/admin_park_equipments/position.haml
.well-sm
  %h2
    %center Администрирование справочника должностей
=render 'menu'
.well
  .field_input
    %p{:align => "left"}
      %i
        Чтобы отредактировать данные, щелкните по нужной записи
    - if @positions.present?
      %table.table.table-editable
        -@positions.each do |position|
          %tr
            %td
              =best_in_place position, :name, path: edit_position_admin_park_equipment_path(position.id)

            %td
              = link_to delete_position_admin_park_equipments_path(id: position.id), data: { confirm: "Точно удалить?"}, class: "btn btn-sm btn-danger" do
                %i.fa.fa.fa-trash-o

.well
  .field_input
    =form_for(@position, url: create_position_admin_park_equipments_path) do |f|
      = f.label :name, "Название должности", class: "form-control"
      = f.text_field :name, class: "form-control"
      = f.submit "добавить должность", class: "btn btn-sm btn-primary"